### ISSUE TITLE
CSV file not found

### ISSUE THREAD

**Issue by lemmonation** [rootnx/UniCoRN#1]
Hi authors, thanks for the great work! I'm trying to run the code, but I find that this [line](https://github.com/rootnx/UniCoRN/blob/77cc34da22af5a6dcc3723fa442168f07e75dd10/src/dataset/fMRI_datasets.py#L132) reads a csv file from the preprocessed MNI_to_TRs dir, which does not exist. Do you know how to get this file? I find that "self.stimuli_path" is not utilized in the script.

Thanks!

**Comment by rootnx** [comment]
please read the README, the data path needs to be self-configured, also the self.stimuli_path is not utilized indeed as we use "gentle_path"  here to read the stimuli.

**Comment by lemmonation** [comment]
I have read the Readme file and run the `preprocess_hasson.py` script, which only generates two normalized directories in `MNI_to_TRs/{subj}`. No `{}_task-{}_align.csv` file is generated.

**Comment by rootnx** [comment]
you need to first self-configure the data directory in the code

**Comment by lemmonation** [comment]
of course I have self-configured the data path. you should provide more detailed preprocessing steps in the readme then

**Comment by rootnx** [comment]
of course
